language: cpp
os: linux
dist: bionic
compiler: gcc

_build_job_linux: &build_job_linux
  addons:
    apt:
      packages:
        - cmake
        - build-essential
        - mesa-common-dev
        - libglfw3
        - libglfw3-dev
        - libglew-dev
  script:
    - cd platforms/Linux
    - export CXXFLAGS="-DBUILD_TEST_MODE"
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - cmake --build .

# =============================================================================================================================================================
jobs:
  include:
  # Architectures ==============================================================================================================================================================
    - stage: Build engine (Architectures Test) (only Linux)
      # arm64
      if: (branch = master)
      name: "arm64 (v8)"
      arch: arm64
      os: linux
      dist: bionic
      <<: *build_job_linux
      #==============================================================================================================================================================
    - # arm64-graviton2
      if: (branch = master) OR (branch = build_testing)
      arch: arm64-graviton2
      name: "arm64-graviton2 (v8)"
      os: linux
      dist: bionic
      <<: *build_job_linux
#==============================================================================================================================================================
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
