language: cpp
dist: bionic
os:
  - linux
compiler:
  - gcc

jobs:
  include:
    stage: BuildEngine
    if: branch = master
    name: "Build Engine"
    before_install:
      # Setting Environment
      - sudo apt-get update
      - sudo apt-get -y install cmake build-essential mesa-common-dev libglfw3 libglfw3-dev libglew-dev
    script:
      - cd platforms/Linux
      - export CXXFLAGS="-DBUILD_TEST_MODE"
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug ../
      - cmake --build .
    after_success:
      - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
      - chmod +x send.sh
      - ./send.sh success $WEBHOOK_URL
    after_failure:
      - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
      - chmod +x send.sh
      - ./send.sh failure $WEBHOOK_URL
