name: MacOS Build


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:
    strategy:
      matrix:
          macos-version: [ macos-12, macos-11 ]
          compiler: [ clang ]
          include:
            - compiler: clang
              compiler-CXX: clang++
              
    runs-on: ${{ matrix.macos-version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install packages
        run: |
          brew install cmake ninja glfw
          ninja --version
          cmake --version
          
      - name: Ready for build
        run: |
          export CXXFLAGS="-DBUILD_TEST_MODE"
          mkdir build
        working-directory: ./platforms/MacOS
        
      - name: Configure Cmake
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler-CXX }}
        run: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug ../
        working-directory: ./platforms/MacOS/build
        
      - name: Build
        run: cmake --build .
        working-directory: ./platforms/MacOS/build
