name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    strategy:
      matrix:
          linux-version: [ubuntu-latest, ubuntu-18.04]
          compiler: [gcc, clang]
          include:
            - compiler: gcc
              compiler-CXX: g++
            - compiler: clang
              compiler-CXX: clang++
              
    runs-on: ${{ matrix.linux-version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install packages
        run: |
          sudo apt-get -y install cmake build-essential mesa-common-dev libglfw3 libglfw3-dev libglew-dev
          
      - name: Ready for build
        run: |
          export CXXFLAGS="-DBUILD_TEST_MODE"
          mkdir build
        working-directory: ./platforms/Linux
        
      - name: Configure Cmake
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler-CXX }}
        run: cmake -DCMAKE_BUILD_TYPE=Debug ../
        working-directory: ./platforms/Linux/build
        
      - name: Build
        run: cmake --build .
        working-directory: ./platforms/Linux/build
